# Generated by Django 3.0.7 on 2022-10-03 15:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plumbing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('flat_no', models.CharField(max_length=255)),
                ('building_names', models.CharField(max_length=255)),
                ('type_of_services', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 10, 3, 15, 39, 30, 87722, tzinfo=utc))),
                ('message', models.TextField()),
                ('purpose', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
