# Generated by Django 3.0.7 on 2022-10-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plumbing',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
