# Generated by Django 4.1 on 2022-10-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_furniture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accodition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('flat_no', models.CharField(max_length=255)),
                ('building_names', models.CharField(max_length=255)),
                ('type_of_services', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('message', models.TextField()),
                ('purpose', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
